!!python/object:argparse.Namespace
adam_beta1: 0.9
adam_beta2: 0.999
batch_size: 4
best_val_metric: succ_rate
bn_momentum: 0.05
clip_weight_thresh: 0.05
dataset: ThreeDMatchPairDataset03
dist_type: L2
eval_registration: true
exp_gamma: 0.99
fast_validation: false
feat_conv1_kernel_size: 3
feat_model: SimpleNetBN2C
feat_model_n_out: 16
hit_ratio_thresh: 0.1
icp_cache_path: icp
inlier_conv1_kernel_size: 3
inlier_direct_loss_weight: 1.0
inlier_feature_type: ones
inlier_knn: 1
inlier_model: ResUNetBN2C
inlier_use_direct_loss: true
iter_size: 1
kitti_date: '2011_09_26'
kitti_dir: null
kitti_max_time_diff: 3
knn_search_method: gpu
lr: 0.1
max_epoch: 100
max_scale: 1.2
min_scale: 0.8
momentum: 0.8
nn_max_n: 250
normalize_feature: true
num_train_iter: -1
optimizer: SGD
out_dir: outputs
pcd0: redkitchen_000.ply
pcd1: redkitchen_010.ply
positive_pair_search_voxel_size_multiplier: 1.5
procrustes_loss_weight: 1.0
resume: null
resume_dir: null
rotation_range: 360
save_epoch_freq: 1
scheduler: ExpLR
sgd_dampening: 0.1
sgd_momentum: 0.9
stat_freq: 40
success_rre_thresh: 15
success_rte_thresh: 0.3
test_num_workers: 2
test_phase: test
test_random_crop: false
test_random_rotation: false
test_valid: true
threed_match_dir: ./data
train_num_workers: 2
train_phase: train
trainer: WeightedProcrustesTrainer
trans_weight: 1
use_balanced_loss: false
use_gpu: true
use_random_rotation: true
use_random_scale: false
use_xyz_feature: false
val_batch_size: 1
val_epoch_freq: 1
val_max_iter: 400
val_num_workers: 1
val_phase: val
voxel_size: 0.025
weight_decay: 0.0001
# weights: ./pretrained/ResUNetBN2C-feat32-3dmatch-v0.05.pth
weights: ../DeepGlobalRegistration/pretrained/ResUNetBN2C-feat32-3dmatch-v0.05.pth
weights_dir: null
